PierreTreat/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierreTreat.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "Treat type can't be empty.")]
    public string TreatType { get; set; }
    public List<TreatFlavor> JoinEntities { get; set; }
  }
}

PierreTreat/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierreTreat.Models;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreTreat.Controllers
{
  public class TreatsController : Controller
  {
    private readonly PierreTreatContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierreTreatContext db)
    {
      _db = db;
      _userManager = userManager;
    }

    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      if (currentUser != null)
      {
        if (!ModelState.IsValid)
        {
          return View(treat);
        }
        else
        {
          _db.Treats.Add(treat);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      else
      {
        return View(treat);
      }
    }

    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public async Task<ActionResult> AddFlavor(Treat treat, int flavorId)
    {
      string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      if (currentUser != null)
      {
        #nullable enable
        TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
        #nullable disable
        if (joinEntity == null && flavorId != 0)
        {
          _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
          _db.SaveChanges();
        }
        return RedirectToAction("Details", new { id = treat.TreatId });
      }
      else
      {
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
        return View(treat);
      }
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(Treat treat)
    {
      string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      if (currentUser != null)
      {
        if (!ModelState.IsValid)
        {
          return View(treat);
        }
        else
        {
          _db.Treats.Update(treat);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      else
      {
        return View(treat);
      }
    }

    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<ActionResult> DeleteConfirmed(int id)
    {
      string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      if (currentUser != null)
      {
        Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
        _db.Treats.Remove(thisTreat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return View(id);
      }
    }

    [HttpPost]
    public async Task<ActionResult> DeleteJoin(int joinId)
    {
      string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      if (currentUser != null)
      {
        TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
        _db.TreatFlavors.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return View(joinId);
      }
    }
  }
}

PierreTreat/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierreTreat.Models.Treat

<h2>Add a flavor</h2>

@if (User.Identity.IsAuthenticated)
{
  <h4>Add a flavor to this treat: @Html.DisplayFor(model => model.TreatType)</h4>
  
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
  }
}
else
{
  <p>Please @Html.ActionLink("log in", "LogIn", "Account") to add a flavor to this treat: @Html.DisplayFor(model => model.TreatType)</p>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierreTreat/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierreTreat.Models.Treat;

<h4>Add a new treat</h4>

@if (!ViewData.ModelState.IsValid)
{
  @Html.ValidationSummary("Please fix the following error(s) and then resubmit form:")
}

@if (User.Identity.IsAuthenticated)
{
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.TreatType)
    @Html.TextBoxFor(model => model.TreatType)

    <input type="submit" value="Add new treat" class="btn btn-default" />
  }
}
else
{
  <p>Please @Html.ActionLink("log in", "LogIn", "Account") to create a new treat.</p>
}

<p>@Html.ActionLink("Show all treats", "Index")</p>

PierreTreat/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierreTreat.Models.Treat

@if (User.Identity.IsAuthenticated)
{
  <h2>Are you sure you want to delete this?</h2>

  <p>Treat: @Html.DisplayFor(model => model.TreatType)</p>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
}
else
{
  <p>Please @Html.ActionLink("log in", "LogIn", "Account") to delete this treat: @Html.DisplayFor(model => model.TreatType).</p>
}

PierreTreat/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierreTreat.Models
@model PierreTreat.Models.Treat

<h3>@Html.DisplayFor(model => model.TreatType)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat does not have any flavors yet.</p>
}
else
{
  <h4>This treat has the following flavors:</h4>
  if (!User.Identity.IsAuthenticated)
  {
    <p>Must be @Html.ActionLink("logged in", "LogIn", "Account") in order to remove flavor(s) from treat.</p>
  }
  <ul>
    @foreach(TreatFlavor join in Model.JoinEntities)
    {
      <li>@join.Flavor.FlavorName</li>
        @using (Html.BeginForm("DeleteJoin", "Treats"))
        {
          @Html.Hidden("joinId", @join.TreatFlavorId)
          if (User.Identity.IsAuthenticated)
          {
            <input type="submit" value="Remove flavor from treat" />
          }
        }
    }
  </ul>
}

<p>@Html.ActionLink("Add a flavor", "AddFlavor", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Edit treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Delete treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

PierreTreat/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierreTreat.Models.Treat

<h2>Edit</h2>

@if (User.Identity.IsAuthenticated)
{
  <h4>Edit this treat: @Html.DisplayFor(model => model.TreatType)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    @Html.LabelFor(model => model.TreatType)
    @Html.EditorFor(model => model.TreatType)

    <input type="submit" value="Save" />
  }
}
else
{
  <p>Please @Html.ActionLink("log in", "LogIn", "Account") to edit this treat: @Html.DisplayFor(model => model.TreatType).</p>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierreTreat/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierreTreat.Models;

<h1>Treats</h1>

@if (Model.Count == 0)
{
  <h3>No treats have been added yet.</h3>
}
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.TreatType}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>